language: objective-c
os: osx
osx_image: xcode9.4
sudo: required
python: '3.6'
git:
  depth: 1
branches:
  only:
  - master

env:
  global:
  - BUILD_VERSION="0.4.0"

before_install:
- brew install python3 --framework
- python3 -m venv venv
- source venv/bin/activate
- python3 -m pip install -U pip
- python3 -m pip install PyInstaller>=3.6

install:
- wget https://github.com/namuan/one-page/archive/${BUILD_VERSION}.tar.gz -O ./onepage.tar.gz
- tar -xvf ./onepage.tar.gz
- mv one-page-${BUILD_VERSION}/* .
- rm -rf onepage.tar.gz one-page-${BUILD_VERSION}
- python3 -m pip install -r requirements/base.txt

script:
- make package
# - ./mac-codesign.sh
- cd dist && zip "${TRAVIS_BUILD_DIR}"/onepage-macos-${BUILD_VERSION}.zip -r onepage.app && cd ..
- echo "Done!"

notifications:
  email: false

before_deploy:
- git config --local user.name "namuan"
- git remote set-url origin https://namuan:${GITHUB_TOKEN}@github.com/namuan/one-page-releases.git
- git push origin :refs/tags/${BUILD_VERSION}
- git tag -f -am v${BUILD_VERSION} ${BUILD_VERSION}

deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file: "${TRAVIS_BUILD_DIR}/onepage-macos-${BUILD_VERSION}.zip"
  overwrite: true
  skip_cleanup: true
  on:
    repo: namuan/one-page-releases